version: '3.9'
services:
  #  Golang Rest Api
  app:
    container_name: go-rest
    build:
      dockerfile: ./docker/golang/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - mynet
    depends_on:
      - db
  # Mysql Database
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'goRest'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - mynet
networks:
  mynet:
    driver: 'bridge'
